#!/usr/bin/python

'Setting the position of nodes'

from mininet.net import Mininet
from mininet.node import Controller, OVSKernelAP
from mininet.link import TCLink
from mininet.cli import CLI
from mininet.log import setLogLevel

def topology():

    "Create a network."
  net = Mininet_wifi(controller=Controller, accessPoint=OVSKernelAP)
info("*** Creating nodes\n")
net.addStation('sta1', mac='00:00:00:00:00:02', ip='10.0.0.1/8',
position='20,40,0')
net.addStation('sta2', mac='00:00:00:00:00:03', ip='10.0.0.2/8',
position='40,60,0')
net.addStation('sta3', mac='00:00:00:00:00:04', ip='10.0.0.3/8',
position='90,70,0')
net.addStation('sta4', mac='00:00:00:00:00:05', ip='10.0.0.4/8',
position='140,90,0')
ap1 = net.addAccessPoint('ap1', ssid='new-ssid1', mode='g', channel='1',
position='40,40,0')
ap2 = net.addAccessPoint('ap2', ssid='new-ssid2', mode='g', channel='1',
position='140,900,0')
c1 = net.addController('c1', controller=Controller)
h1 = net.addHost('h1', ip='10.0.0.6/8')
h2 = net.addHost('h2', ip='10.0.0.7/8')


    print "*** Configuring wifi nodes"
    net.configureWifiNodes()

    print "*** Creating links"
    net.addLink(ap1, h1)

    net.plotGraph(max_x=500, max_y=500)

    print "*** Starting network"
    net.build()
    c1.start()
    ap1.start([c1])

    print "*** Running CLI"
    CLI(net)

    print "*** Stopping network"
    net.stop()


if __name__ == '__main__':
    setLogLevel('info')
    topology()

2 não pq a estação conectados são diferentes
